// src/components/preact/JsonPlaceHolder.jsx
import { useState, useEffect } from "preact/hooks";
import PicoSkeleton from "../pico/PicoSkeleton";
import axios from "axios";

export default function JsonPlaceHolder() {
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    async function fetchData() {
      try {
        setLoading(true);
        setError(null);
        const response = await axios.get(
          "https://jsonplaceholder.typicode.com/posts/1/comments"
        );
        const comments = response.data;
        setData(comments);
      } catch (error) {
        if (error instanceof Error) {
          setError(error.message);
        }
      } finally {
        setLoading(false);
      }
    }

    fetchData();
  }, []);
  return (
    <>
      {loading && <PicoSkeleton />}
      {error && <p>Error: {error}</p>}
      {data && (
        <ol>
          {data.map((comment) => {
            return <li key={comment.id}>{comment.name}</li>;
          })}
        </ol>
      )}
    </>
  );
}

// src/components/vue/JsonPlaceHolder.vue
<template>
  <div v-if="isLoadings">Loading...</div>
  <ol v-else>
    <li v-for="item in data" :key="item.id">
      {{ item.name }}
    </li>
  </ol>
</template>

<script setup lang="ts">
import { ref } from "vue";
import axios from "axios";

const data = ref([]);
const isLoadings = ref(false);

const fetchData = async () => {
  isLoadings.value = true;
  try {
    const response = await axios.get(
      "https://jsonplaceholder.typicode.com/posts/2/comments"
    );
    data.value = response.data;
  } catch (error) {
  } finally {
    isLoadings.value = false;
  }
};

fetchData();
</script>
